server:
  port: 8282

spring:
  application:
    name: proveedor-catalog
  data:
    mongodb:
      #uri: mongodb://cosmosdbsf:lHEVlSpr8jkT8QSWjTEHbwgVx9bbPQ2BpypBK54F61vcCKP0sjnBzON2Z1eHZLBwKKoCPOkfrykR2kZwDQv91A==@cosmosdbsf.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
      #database: falabellaData
      uri: mongodb://api-tottus-retail:LeOtssdONt4wa9a2m2YpxGkquaDS0vzdJlKw5hsGcrv6sPvYmRU2qJSANRS7pCtWV960XYx0aO99zbB3tVrz6A==@api-tottus-retail.documents.azure.com:10255/?ssl=true&replicaSet=globaldb
      database: tottus
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
publisher:
  #endpoint: Endpoint=sb://tot-corp-orion-int-qa.servicebus.windows.net/;SharedAccessKeyName=totorionadm;SharedAccessKey=+uHMYKcSeBfapKNgfqLkXuQe8fgpz2GR4GGKkChZB4s=;EntityPath=tot-corp-orion-pricechanges-topic-mid
  #endpoint: Endpoint=sb://ttotus-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=/pktePJ8YZk3jyyaxtExbDbn9+V5fEOPPxIXPEkO9rI=;EntityPath=topic-product
  endpoint: Endpoint=sb://ttotus-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=/pktePJ8YZk3jyyaxtExbDbn9+V5fEOPPxIXPEkO9rI=;EntityPath=topic-provider-ext
  azure-service-bus:
    #topic: tot-corp-orion-pricechanges-topic-mid
    topic: topic-provider-ext
    #topic: topic-product

provider:
  param:
    rut:
      max-lenght: 20
    dvRut:
      max-lenght: 3
    nameVendor:
      max-lenght: 80
    address:
      max-lenght: 200
    currencycode:
      max-lenght: 10
    city:
      max-lenght: 50
    country:
      max-lenght: 50
    country-code:
      max-lenght: 50
    phone-area-code:
      max-lenght: 10
    phone-number:
      max-lenght: 20
    fax-number:
      max-lenght: 30
    zip-code:
      max-lenght: 30
    email:
      max-lenght: 50
      format: "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$"
    comuna:
      max-lenght: 30
    type-vendor:
      max-lenght: 20
    
azure:
  redis:
    host: tottus.redis.cache.windows.net
    key: KFr4tHPRV5s0FOXzF2kMEPXSxDhCJitdEOVdAxseOBc=
    port: 6380
  
#debug: true  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  